# Generated by Django 4.2.30 on 2026-09-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_description_alter_event_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='venue_object',
            new_name='venue',
        ),
    ]
