# Generated by Django 4.2.30 on 2026-09-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_date_event_event_date_rename_title_event_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='host',
            new_name='manager',
        ),
    ]
