# Generated by Django 4.2.30 on 2026-09-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_venue_email_venue_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Venue Owner'),
        ),
    ]
